### ISSUE TITLE
Cannot inject urls in 1.7.10 mods server

### ISSUE THREAD

**Issue by PonyPC** [to2mbn/authlib-injector#1]
Cannot inject urls in 1.7.10 mods server, it seems that the transform unit can only find strings in main jar instead of libraries. The mojang authlib is located at libraries folder.

**Comment by yushijinhun** [comment]
> it seems that the transform unit can only find strings in main jar instead of libraries.

Nope. If you use the `-javaagent` parameter to do the injection work, it should work no matter where the class file is.

Could you provide the console output?

**Comment by PonyPC** [comment]
I use it as a mod in server. Is there any way to work without javaagent parameter.

**Comment by yushijinhun** [comment]
Loading authlib-injector as a mod on the server side hasn't been tested yet, which will fall when the classes of authlib are loaded before this mod. So you'd better use authlib-injector as a javaagent.

If you still want to use authlib-injector in that way, see [authlib-injector.example.yaml](https://github.com/to2mbn/authlib-injector/blob/master/authlib-injector.example.yaml) and check whether you have configured it correctly.

**Comment by 122474363** [comment]
java -javaagent:C:\Users\Administrator\Desktop\未来时代\minecraft\authlib_injector.jar=@https://authserver.xxx.com/
单独使用可以正常返回网页，但是使用hmcl的时候正版登录无效，抓包分析链接依旧指向mojang，而且必须要绝对路径？

**Comment by Indexyz** [comment]
@122474363 是否给hmcl上了javaagent

**Comment by 122474363** [comment]
目前已经正确了。但是出现的问题是服务器内有一个人 如果在登录另一个人就会都掉线 @Indexyz

**Comment by Indexyz** [comment]
@122474363 有后台报错么? 这部分好像是服务端的关系吧（

**Comment by 122474363** [comment]
@Indexyz 找到问题了是 key的问题，，但是现在出现一个奇怪的问题，。就是有些客户登录的时候会一直显示登录中。。。
