### ISSUE TITLE
关于公钥长度问题

### ISSUE THREAD

**Issue by xiaonian233** [to2mbn/authlib-injector#11]
用的bs上的yggdrasil api 2.0.1
https://wwdmcc.cn/skin/api/yggdrasil/
公钥用的是网站给出的
-----BEGIN PUBLIC KEY-----
..............
-----END PUBLIC KEY-----
游戏验证没问题，加载皮肤出现

![image](https://user-images.githubusercontent.com/21072615/39403636-f7221eb2-4bb2-11e8-9046-0f1bcbf54388.png)

**Comment by yushijinhun** [comment]
已确认是 authlib-injector 版本过低的问题。

**Comment by yushijinhun** [comment]
@huanghongxun HMCL 是否有更新 authlib-injector 的措施？

**Comment by huanghongxun** [comment]
会检查CI的buildinfo的

**Comment by reserveword** [comment]
我最近遇到了一个类似的问题，服务器用的是旧版的authlib-injector，我用的是新版的，抛出的错误和这个issue类似，请问是否可以让客户端向下兼容服务器？

**Comment by yushijinhun** [comment]
@reserveword 请更新到最新的 authlib-injector。

**Comment by reserveword** [comment]
> 
> 
> @reserveword 请更新到最新的 authlib-injector。

客户端是最新的authlib-injector，服务器不在我的掌控范围之内

**Comment by hempflower** [comment]
> 客户端是最新的authlib-injector，服务器不在我的掌控范围之内     

1. 向服务器管理人员反馈      
2. 将自己的authlib-injector回滚到旧版本
