### ISSUE TITLE
可否在wiki“材质 URL 规范”部分公布示例图片的缓冲区内容

### ISSUE THREAD

**Issue by PixelGalaxy** [to2mbn/authlib-injector#14]
本人在使用Python实现该API时，计算得出示例图片的二进制值为：
`\x00\x00\x00\x02\x00\x00\x00\x03\xff\xff\x00\x00\xff\x00\xff\x00\xff\x00\x00\xff\x00\x00\x00\x00\xff\xff\x00\xff\xff\xff\xff\x00`，即
图片宽度`\x00\x00\x00\x02`，高度`\x00\x00\x00\x03`，像素部分`\xff\xff\x00\x00` 
`\xff\x00\xff\x00` `\xff\x00\x00\xff` `\x00\x00\x00\x00` `\xff\xff\x00\xff` `\xff\xff\xff\x00`共6个像素，
是示例图片从从左往右，从上至下先横后纵的扫描结果。
但计算出的sha256值与示例不符。
故欲与您计算哈希之前的缓冲区二进制值作比对。
自己初入GitHub及Python大坑，若本人对您wiki的理解有误，还请斧正。

**Comment by yushijinhun** [comment]
缓冲区内数据应该是这样的：
```
00 00 00 02  00 00 00 03  FF FF 00 00  FF 00 00 FF
FF FF 00 FF  FF 00 FF 00  00 00 00 00  FF FF FF 00
```
扫描顺序是先纵后横，即 `(0,0)`, `(0,1)`, `(0,2)`, `(1,0)`, `(1,1)`, `(1,2)`。

**Comment by yushijinhun** [comment]
已添加缓冲区内容示例。[6ce12d3618dbbc761e6d0f376e5ec141db01cb93](https://github.com/to2mbn/authlib-injector/wiki/Yggdrasil%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83/_compare/a84d9f25383ca3b7ae65929113ff560b0ae0e5e2...6ce12d3618dbbc761e6d0f376e5ec141db01cb93)
