### ISSUE TITLE
这个不支持皮肤站的API吗？

### ISSUE THREAD

**Issue by 122474363** [to2mbn/authlib-injector#2]
这个不支持皮肤站的API吗？

**Comment by yushijinhun** [comment]
你说的皮肤站指的是？

**Comment by 122474363** [comment]
http://www.mcbbs.net/thread-718219-1-1.html
大佬请看。

**Comment by yushijinhun** [comment]
这是个历史遗留问题。

本项目前身是authlib-agent。我当时写authlib-agent也就是随便写写，整个项目设计的很糟糕。后来authlib-agent被其它不少项目使用（包括那个blessing skin server），随之也暴露出很多弊端，我就考虑重新设计。然后新开了这个authlib-injector项目，希望它能取代authlib-agent。

至于你说的问题，显然应该是blessing skin server去支持authlib-injector，而不是authlib-injector去支持blessing skin server。
这一点我以前就和blessing skin server的作者 @621sama 聊过，希望他能把api切换到authlib-injector上来。不过因为学业原因，他几乎没有精力开发blessing skin server，这件事也就拖到了现在。

**Comment by 122474363** [comment]
@yushijinhun 现在发生一个奇怪的问题，就是我的电脑测试登录正常，，而别的电脑启动器正常，但是游戏登录的时候一直显示登录中。。。。
