### ISSUE TITLE
未定义与实现皮肤的传统加载接口

### ISSUE THREAD

**Issue by xfl03** [to2mbn/authlib-injector#7]
**接口用途** 用户名 -> 皮肤材质
**接口地址** http://skins.minecraft.net/MinecraftSkins/{USERNAME}.png
**调用位置** net.minecraft.client.entity.AbstractClientPlayer.getDownloadImageSkin(ResourceLocation resourceLocationIn, String username)
**调用情况** 已知用于旁观模式菜单(SpectatorMenu)中的头像加载

CustomSkinLoader目前暂时采用[曲线救国的方案](https://github.com/xfl03/MCCustomSkinLoader/blob/csl-14/Common/source/customskinloader/fake/FakeClientPlayer.java)将其转移到SkinManager调用已定义的接口加载材质  
望您可以定义并实现这一接口

**Comment by yushijinhun** [comment]
我在wiki上找到了这个api的介绍：[Skin/Creating a skin](https://minecraft.gamepedia.com/index.php?title=Skin&oldid=1181426#Creating_a_skin)。
但似乎无论将`http://skins.minecraft.net/MinecraftSkins/{username}.png`中的`username`替换为何值，返回总是404？

**Comment by yushijinhun** [comment]
`https://status.mojang.com/check`报告`skins.minecraft.net`不可用（red）。
在Mojang的这个API恢复正常之前，不会修复该bug。

**Comment by yushijinhun** [comment]
上游相关issues: [MC-125157](https://bugs.mojang.com/browse/MC-125157), [WEB-985](https://bugs.mojang.com/browse/WEB-985)

**Comment by yushijinhun** [comment]
上游看起来是不会修复这个bug了。但是既然Mojang都已经弃用这个api了，我们再把它加进文档就有些不妥。 

我现在有一个想法，在本地启动一个http server，将到该api的请求转发到此http server处理，这样就不必麻烦服务端了。但如果这样，这么一个功能是放在authlib-injector中，还是另外开一个项目呢？

**Comment by andylizi** [comment]
好像已经有人这么做了。
https://www.superfuntime.org/forum/index.php/topic,183323.new.html
https://github.com/blalp/replacement-for-minecraft-lagacy-skin-servers

**Comment by yushijinhun** [comment]
不一样。这些解决方案都是把原来到skins.minecraft.net的请求引导到他们自己服务器上，但这对authlib-injector是无效的，因为最后请求被发到了mojang。

**Comment by xfl03** [comment]
@andylizi
如果仅需要修复旁观模式菜单中头颅的加载，使用 14.8 版本的 CustomSkinLoader 即可，且兼容 Authlib-injector 。  
不过，这样使用第三方程序变相请求，怕是有点与 Authlib-injector 的一些理念有些不符，还是希望能有另一种解决方案。
我建议是将其标注为可选 API ，让实现者的需求决定是否需要使用这一 API 。

**Comment by yushijinhun** [comment]
已经修复。可以从[这里](https://ci.to2mbn.org/job/authlib-injector/14/)下载最新的构建输出。
