### ISSUE TITLE
服务器内其他玩家皮肤看不见  emmm

### ISSUE THREAD

**Issue by MyTol** [to2mbn/authlib-injector#8]
只能看见自己的皮肤. 其他玩家全是Alex皮肤. 啥情况呢 用的是blessing-skin-server的插件做后端

**Comment by yushijinhun** [comment]
请问你使用的Minecraft是何版本？如果使用[yggdrasil-mock](https://github.com/to2mbn/yggdrasil-mock)作为后端，能否正常显示？

**Comment by yushijinhun** [comment]
已超过一周未收到用户回复，该 issue 做关闭处理。
