### ISSUE TITLE
移除 org.json 依赖

### ISSUE THREAD

**Issue by yushijinhun** [to2mbn/authlib-injector#9]
[`org.json`](https://github.com/stleary/JSON-java) 的许可证中包含以下内容：
```
The Software shall be used for Good, not Evil.
```
这可能会给本项目带来法律问题。需要将 `org.json` 依赖移除，并寻找一个替代品。

另见：  stleary/JSON-java#353

**Comment by yushijinhun** [comment]
可使用 [android-json](https://mvnrepository.com/artifact/com.vaadin.external.google/android-json) 作为替代。

**Comment by xfl03** [comment]
原来 authlib-inject 算是做了称得上 Evil 的事情啊..

**Comment by ustc-zzzz** [comment]
那么按照楼上的标准来看，authlib-injector 绝对算是做了称得上 Evil 的事情。通过绕过登录系统，玩家可以轻易地使用非正版账户玩 MC 服务器，而且我觉得大部分用 ai 的服务器也都是为了这么做。

**Comment by yushijinhun** [comment]
```
authlib-injector 绝对算是做了称得上 Evil 的事情。
```
感谢您的肯定，这是我的荣幸。

**Comment by yushijinhun** [comment]
如果换用 android-json，是否需要对其进行裁剪？原来使用 org.json 的时候，我是把类库裁剪到最小的。

**Comment by andylizi** [comment]
这个我个人感觉无所谓吧。毕竟现代的网速和硬盘空间早已不是问题了。何况那个库本来就没多大。
